import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b">
        <div className="container mx-auto px-4 py-4">
          <Link href="/" className="text-2xl font-bold text-blue-600">
            FratGPT 2.0
          </Link>
        </div>
      </header>

      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        <div className="prose max-w-none space-y-6 text-gray-700">
          <p className="text-sm text-gray-500">Last updated: January 2025</p>

          <section>
            <h2 className="text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using FratGPT ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">2. Service Description</h2>
            <p>
              FratGPT provides AI-powered homework assistance through a web application and Chrome extension.
              The Service uses multiple AI models to help students understand and solve academic problems.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">3. Subscription Plans</h2>
            <p>We offer three subscription tiers:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Free:</strong> 20 solves per day, $0/month</li>
              <li><strong>Basic:</strong> 50 solves per day, $9/month</li>
              <li><strong>Pro:</strong> 500 solves per day, $19/month</li>
            </ul>
            <p className="mt-4">
              Daily limits reset at midnight UTC. Paid subscriptions are billed monthly through Stripe.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">4. Acceptable Use</h2>
            <p>You agree NOT to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the Service to cheat on exams or violate academic integrity policies</li>
              <li>Share your account credentials with others</li>
              <li>Abuse or attempt to circumvent usage limits</li>
              <li>Upload harmful, offensive, or illegal content</li>
              <li>Reverse engineer or attempt to extract AI models</li>
              <li>Use the Service for any commercial purpose without permission</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">5. Academic Integrity</h2>
            <p>
              <strong>Important:</strong> FratGPT is designed as a learning aid to help you understand concepts.
              Using our Service to complete assignments without understanding the material may violate your
              institution's academic integrity policies. You are responsible for following your school's rules.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">6. Payment and Refunds</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>Subscriptions are billed monthly in advance</li>
              <li>You can cancel anytime; access continues until the end of your billing period</li>
              <li>Refunds are provided at our discretion on a case-by-case basis</li>
              <li>Failed payments may result in service suspension</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">7. Service Availability</h2>
            <p>
              We strive for 99% uptime but do not guarantee uninterrupted service. We may:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Perform maintenance that temporarily disrupts service</li>
              <li>Modify or discontinue features with notice</li>
              <li>Suspend accounts that violate these terms</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">8. AI-Generated Content</h2>
            <p>
              AI responses are generated by third-party AI models (Google Gemini, OpenAI, Anthropic).
              While we strive for accuracy, AI can make mistakes. You should:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Verify important information independently</li>
              <li>Use answers as learning aids, not absolute truth</li>
              <li>Understand that AI may occasionally produce incorrect or nonsensical responses</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">9. Data Retention</h2>
            <p>
              We automatically delete uploaded images after 5 days. Chat history is retained for your
              convenience but can be deleted upon request.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">10. Termination</h2>
            <p>
              We reserve the right to suspend or terminate accounts that violate these terms, abuse the
              service, or engage in fraudulent activity.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">11. Limitation of Liability</h2>
            <p>
              FratGPT is provided "as is" without warranties. We are not liable for:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Incorrect AI responses or academic consequences</li>
              <li>Service interruptions or data loss</li>
              <li>Third-party AI provider outages</li>
              <li>Any indirect or consequential damages</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">12. Changes to Terms</h2>
            <p>
              We may update these terms at any time. Continued use of the Service after changes
              constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">13. Contact</h2>
            <p>
              Questions about these terms? Contact us at{' '}
              <a href="mailto:support@fratgpt.com" className="text-blue-600 hover:underline">
                support@fratgpt.com
              </a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t">
          <Link href="/" className="text-blue-600 hover:underline">
            ← Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
